server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: clientes
          uri: lb://CLIENTES
          predicates:
            - Path=/api/v1/clientes/**

        - id: peliculas
          uri: lb://PELICULAS
          predicates:
            - Path=/api/v1/peliculas/**

        - id: juegos
          uri: lb://JUEGOS
          predicates:
            - Path=/api/v1/juegos/**

        - id: reservas
          uri: lb://RESERVAS
          predicates:
            - Path=/api/v1/reservas/**

        - id: reclamos
          uri: lb://RECLAMOS
          predicates:
            - Path=/api/v1/reclamos/**

        - id: resenas
          uri: lb://RESENAS
          predicates:
            - Path=/api/v1/resenas/**

        - id: multas
          uri: lb://MULTAS
          predicates:
            - Path=/api/v1/multas/**

        - id: pagos
          uri: lb://PAGOS
          predicates:
            - Path=/api/v1/pagos/**

        - id: cupones
          uri: lb://CUPONES
          predicates:
            - Path=/api/v1/cupones/**

        - id: sucursales
          uri: lb://SUCURSALES
          predicates:
            - Path=/api/v1/sucursales/**

management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/