spring:
  application:
    name: peliculas

  datasource:
    url: jdbc:mysql://localhost:3306/db_peliculas?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/


  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

server:
  port: 8084

logging:
  level:
    root: INFO
    duoc.peliculas: DEBUG
  file:
    name: logs/peliculas.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"