server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: clientes
          uri: ${CLIENTES_SERVICE_URL:lb://CLIENTES}
          predicates:
            - Path=/api/v1/clientes/**

        - id: peliculas
          uri: ${PELICULAS_SERVICE_URL:lb://PELICULAS}
          predicates:
            - Path=/api/v1/peliculas/**

        - id: juegos
          uri: ${JUEGOS_SERVICE_URL:lb://JUEGOS}
          predicates:
            - Path=/api/v1/juegos/**

        - id: reservas
          uri: ${RESERVAS_SERVICE_URL:lb://RESERVAS}
          predicates:
            - Path=/api/v1/reservas/**

        - id: reclamos
          uri: ${RECLAMOS_SERVICE_URL:lb://RECLAMOS}
          predicates:
            - Path=/api/v1/reclamos/**

        - id: resenas
          uri: ${RESENAS_SERVICE_URL:lb://RESENAS}
          predicates:
            - Path=/api/v1/resenas/**

        - id: multas
          uri: ${MULTAS_SERVICE_URL:lb://MULTAS}
          predicates:
            - Path=/api/v1/multas/**

        - id: pagos
          uri: ${PAGOS_SERVICE_URL:lb://PAGOS}
          predicates:
            - Path=/api/v1/pagos/**

        - id: cupones
          uri: ${CUPONES_SERVICE_URL:lb://CUPONES}
          predicates:
            - Path=/api/v1/cupones/**

        - id: sucursales
          uri: ${SUCURSALES_SERVICE_URL:lb://SUCURSALES}
          predicates:
            - Path=/api/v1/sucursales/**

management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true